name: Clear Actions Cache
on: [ push, pull_request, workflow_dispatch ]
jobs:
  clear:
    name: Clear github actions cache
    runs-on: ubuntu-latest
    steps:
      - uses: MyAlbum/purge-cache@v2
        with:
          max-age: 60 # a minute
          debug: true
